variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"
  GIT_STRATEGY: clone
  PACKAGE_TAG: ""
  PACKAGE_VERSION: "5.7"
  UPDATE_TEST_VERSIONS: "5.0.0"
  MYSQL_ROOT_PASSWORD: toor
  MYSQL_USER: shopware
  MYSQL_PASSWORD: shopware
  MYSQL_DATABASE: shopware

default:
  tags:
    - t3.medium

stages:
  - Build package
  - Testing

Build package:
  image: gitlab.shopware.com:5005/shopware/5/product/image/package-testsuite/package-builder-cli:php74
  stage: Build package
  services:
    - name: mysql:5.7
      alias: mysql
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/shopware.git shopware --depth=1 -b $PACKAGE_VERSION
    - git clone --bare file://$CI_PROJECT_DIR/shopware _build
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/5/product/package-builder.git deploy-script --depth=1
    - ant -f deploy-script/build.xml install update -Ddb.host="mysql" -Ddb.port=3306 -Ddb.name="shopware" -Ddb.user="shopware" -Ddb.password="shopware" -Dgit.repo.url="$CI_PROJECT_DIR/_build" -Dgit.checkout.branch=$PACKAGE_VERSION -Dgit.newtag=$PACKAGE_VERSION.99 -Dgit.newtag_text=""
  artifacts:
    when: on_success
    paths:
      - deploy-script/output/package/*.zip

Install process:
  image: gitlab.shopware.com:5005/shopware/5/product/package-testsuite/docker-cli
  stage: Testing
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  dependencies:
    - Build package
  services:
    - name: docker:18.09.7-dind
      alias: docker
  script:
    - cp deploy-script/output/package/*.zip files/
    - cd docker
    - ./stage_installer.sh $CI_JOB_ID
  artifacts:
    when: always
    paths:
      - tests/logs/mink/*
    reports:
      junit: tests/logs/mink/*.xml


Update process:
  image: gitlab.shopware.com:5005/shopware/5/product/package-testsuite/docker-cli
  tags:
    - m5.large
  stage: Testing
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  variables:
    PACKAGE_VERSION: "5.6.0"
  dependencies:
    - Build package
  services:
    - name: docker:18.09.7-dind
      alias: docker
  script:
    - mv deploy-script/output/package/*.zip files/
    - cd docker
    - ./stage_updater.sh $CI_JOB_ID
  artifacts:
    when: always
    paths:
      - tests/logs/mink/*
    reports:
      junit: tests/logs/mink/*.xml

Test installation:
  image: gitlab.shopware.com:5005/shopware/5/product/package-testsuite/docker-cli
  stage: Testing
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  dependencies:
    - Build package
  services:
    - name: docker:18.09.7-dind
      alias: docker
  script:
    - mv deploy-script/output/package/*.zip files/
    - cd docker
    - ./stage_general.sh $CI_JOB_ID
  artifacts:
    when: always
    paths:
      - tests/logs/mink/*
    reports:
      junit: tests/logs/mink/*.xml
