version: '3.1'

services:
  mysql:
    ports:
      - 3306:3306
  apache:
    ports:
      - 80:80
  smtp:
    ports:
      - 8025:8025
  selenium:
    image: shopware/package-testsuite:selenium-debug
    shm_size: 1G
    links:
      - apache:assetgenerator.example
      - apache:shopware.test
      - apache:shopware-subshop-01.test
    ports:
      - 5900:5900
  tools:
    volumes:
      - ./php:/php-config