version: '2'

volumes:
  datavolume:

services:
  mysql:
    image: mysql
    environment:
       MYSQL_ROOT_PASSWORD: toor
       MYSQL_DATABASE: shopware
       MYSQL_USER: shopware
       MYSQL_PASSWORD: shopware
    ports:
      - 3306:3306
  apache:
      build: ./build-apache
      image: swag/apache-packagetests
      volumes:
        - ../assetgenerator:/var/www/assetgenerator
        - datavolume:/var/www/shopware
        - ~/.composer/cache:/root/.composer/cache
      links:
        - mysql
        - smtp
      extra_hosts:
        - "assetgenerator.example:127.0.0.1"
        - "shopware.test:127.0.0.1"
  smtp:
    image: mailhog/mailhog
  selenium:
    build: ./build-selenium
    image: swag/selenium
    links:
      - apache:assetgenerator.example
      - apache:shopware.test
  tools:
    build: ./build-tools
    image: swag/tools-packagetests
    volumes:
      - ../tests:/tests
      - datavolume:/var/www/shopware
      - ~/.composer/cache:/root/.composer/cache
      - ../files:/source
      - ../tests/logs:/logs
    links:
      - apache:shopware.test
      - apache:assetgenerator.example
      - selenium
      - smtp