volumes:
  datavolume:
  updatesvolume:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    tmpfs:
      - /var/lib/mysql
  apache:
    image: gitlab.shopware.com:5005/shopware/5/product/image/package-testsuite/php-apache:7.4
    volumes:
      - ../www/assetgenerator:/var/www/assetgenerator
      - ../www/updates:/var/www/updates
      - datavolume:/var/www/shopware
      - updatesvolume:/var/www/cdn
      - ../files:/source
      - ../tests:/tests
      - ./php:/php-config:ro
    extra_hosts:
      - "assetgenerator.example:127.0.0.1"
      - "updates.example:127.0.0.1"
      - "cdn.example:127.0.0.1"
      - "shopware.test:127.0.0.1"
      - "shopware-subshop-01.test:127.0.0.1"
    environment:
      SHOPWARE_ENV: testing
      TZ: Europe/Berlin
    links:
      - mysql
  behat:
    image: gitlab.shopware.com:5005/shopware/5/product/image/package-testsuite/php-apache:7.4
    working_dir: /tests
    volumes:
      - ../tests:/tests
      - datavolume:/var/www/shopware
      - updatesvolume:/var/www/cdn
      - ~/.composer/cache:/root/.composer/cache
      - ../files:/source
      - ../tests/logs:/logs
    links:
      - apache:shopware.test
      - apache:shopware-subshop-01.test
      - apache:assetgenerator.example
      - apache:updates.example
      - apache:cdn.example
      - selenium
    entrypoint: [ "/tests/behat" ]
    environment:
      SHOPWARE_ENV: testing
      TZ: Europe/Berlin
  selenium:
    image: selenium/standalone-chrome:85.0
    links:
      - apache:assetgenerator.example
      - apache:shopware-subshop-01.test
      - apache:shopware.test
    shm_size: 1G
    environment:
      TZ: 'Europe/Berlin'
      LANGUAGE: 'de_DE.UTF-8'
      LANG: 'de_DE.UTF-8'
      SCREEN_WIDTH: '1920'
      SCREEN_HEIGHT: '1080'
  wait-for-mysql:
    image: busybox:latest
    entrypoint:
      - sh
    command: >
      -c "
        while !(nc -z mysql 3306)
        do
          echo -n '.'
          sleep 1
        done;
        echo 'database ready!'
      "
    depends_on:
      - mysql
  wait-for-selenium:
    image: busybox:latest
    entrypoint:
      - sh
    command: >
      -c "
        while !(nc -z selenium 4444)
        do
          echo -n '.'
          sleep 1
        done;
        echo 'selenium ready!'
      "
    depends_on:
      - selenium
