services:
  mysql:
    ports:
      - 3306:3306
  apache:
    ports:
      - 80:80
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    shm_size: 1G
    links:
      - apache:assetgenerator.example
      - apache:shopware.test
      - apache:shopware-subshop-01.test
    ports:
      - 5900:5900
