version: '3.1'

volumes:
  datavolume:
  updatesvolume:

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    tmpfs:
      - /var/lib/mysql
  apache:
    image: shopware/package-testsuite:apache7.2
    volumes:
      - ../www/assetgenerator:/var/www/assetgenerator
      - ../www/updates:/var/www/updates
      - datavolume:/var/www/shopware
      - updatesvolume:/var/www/cdn
      - ~/.composer/cache:/root/.composer/cache
    extra_hosts:
      - "assetgenerator.example:127.0.0.1"
      - "updates.example:127.0.0.1"
      - "cdn.example:127.0.0.1"
      - "shopware.test:127.0.0.1"
      - "shopware-subshop-01.test:127.0.0.1"
    environment:
      SHOPWARE_ENV: testing
      TZ: Europe/Berlin
    links:
      - mysql
      - smtp
  smtp:
    image: mailhog/mailhog
  selenium:
    image: shopware/package-testsuite:selenium
    links:
      - apache:assetgenerator.example
      - apache:shopware-subshop-01.test
      - apache:shopware.test
    shm_size: 1G
    environment:
      TZ: Europe/Berlin
  tools:
    image: shopware/package-testsuite:tools7.2
    volumes:
      - ../tests:/tests
      - datavolume:/var/www/shopware
      - updatesvolume:/var/www/cdn
      - ~/.composer/cache:/root/.composer/cache
      - ../files:/source
      - ../tests/logs:/logs
    links:
      - apache:shopware.test
      - apache:shopware-subshop-01.test
      - apache:assetgenerator.example
      - apache:updates.example
      - apache:cdn.example
      - selenium
      - smtp