version: '2'

volumes:
  datavolume:
  updatesvolume:

services:
  mysql:
    extends:
      file: docker-base.yml
      service: mysql
    ports:
      - 3306:3306
  apache:
    extends:
      file: docker-base.yml
      service: apache
    ports:
      - 80:80
    links:
      - mysql
      - smtp
  smtp:
    extends:
      file: docker-base.yml
      service: smtp
    ports:
      - 8025:8025
  selenium:
    build: ./build-selenium-debug
    image: swag/selenium-debug
    shm_size: 1G
    links:
      - apache:assetgenerator.example
      - apache:shopware.test
      - apache:shopware-subshop-01.test
    ports:
          - 5900:5900
  tools:
    extends:
      file: docker-base.yml
      service: tools
    links:
      - apache:shopware.test
      - apache:assetgenerator.example
      - apache:updates.example
      - apache:shopware-subshop-01.test
      - selenium
      - smtp