version: '2'

volumes:
  datavolume:
  updatesvolume:

services:
  mysql:
    extends:
      file: docker-base.yml
      service: mysql
    ports:
      - 3306:3306
  apache:
    extends:
      file: docker-base.yml
      service: apache
    ports:
      - 80:80
    links:
      - mysql
      - smtp
  smtp:
    extends:
      file: docker-base.yml
      service: smtp
    ports:
      - 8025:8025
  selenium:
    extends:
      file: docker-base.yml
      service: selenium
    links:
      - apache:assetgenerator.example
      - apache:shopware.test
  tools:
    extends:
      file: docker-base.yml
      service: tools
    links:
      - apache:shopware.test
      - apache:assetgenerator.example
      - apache:updates.example
      - selenium
      - smtp