version: '2'

volumes:
  datavolume:
  updatesvolume:

services:
  mysql:
    extends:
      file: docker-base.yml
      service: mysql
  apache:
    extends:
      file: docker-base.yml
      service: apache
    links:
      - mysql
      - smtp
  smtp:
    extends:
      file: docker-base.yml
      service: smtp
  selenium:
    extends:
      file: docker-base.yml
      service: selenium
    links:
      - apache:assetgenerator.example
      - apache:shopware-subshop-01.test
      - apache:shopware.test
  tools:
    extends:
      file: docker-base.yml
      service: tools
    links:
      - apache:shopware.test
      - apache:shopware-subshop-01.test
      - apache:assetgenerator.example
      - apache:updates.example
      - apache:cdn.example
      - selenium
      - smtp